#!/usr/bin/perl
# Program:      seq_len
# Programmer:   Sean R. McCorkle, 
#               Biology Department, Brookhaven National Laboratory
# Language:     perl
# Description:  reads fasta-format DNA or protein sequences, prints out 
#               their length (in nt or amino acids)
# 
# Usage:        seq_len [-ftT] [<seq> ...] 
#
#               (stdin used if nothing specified)
#
# Options:
#                -t   terse output - print one sequence length number per line
#                -T   total        - print total count only
#                -f   by file      - report totals for each file
#
#

use  Getopt::Std;

select( ( select(STDOUT), $| = 1 )[0] );
select( ( select(STDERR), $| = 1 )[0] );

die "bad option\n" unless ( getopts( 'ftT' ) );

$count = 0;
$total = 0;
$file_total = 0;

push( @ARGV, "-" ) unless( @ARGV );

foreach my $file ( @ARGV )
   {
    undef( $heading );
    $count = 0;
    $file_total = 0;
    open( INP, $file ) || die "Can't open $file: $@!\n";

    while( $_ = <INP> )
       {
        chomp;
        if ( s/^\>// )
           {
            output_line() if ( defined( $heading ) && (! $opt_T ) && (! $opt_f) );
            $heading = $_ ? $_ : " ";
            $total += $count;
            $file_total += $count;
            $count = 0;
           }
       elsif( /^;/ )
           { next; }
       else
           { 
            s/\s+//g;
            s/^\d*//;
            $count += length( $_ );
           }
      }

    if ( defined( $heading ) )
       {
        output_line() unless ( $opt_T || $opt_f );
        $total += $count;
        $file_total += $count;
       }

    printf "%10d %s\n", $file_total, $file if ( $opt_f );
    close( INP );
   }

print "$total\n" if ( $opt_T );



sub output_line
   {
    printf "%10d ", $count;
    print "$heading" unless ( $opt_t );
    print "\n";
   }
